"""Minimal OpenAI-compatible chat completion client.

The project intentionally avoids depending on the OpenAI SDK in phase 1 so the
file pipeline can run with only the standard library plus pydantic.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any

import json_repair
from pydantic import BaseModel

from law_agent.config import LLMConfig


@dataclass(frozen=True)
class ChatMessage:
    role: str
    content: str


class OpenAICompatibleClient:
    """Small client for `/chat/completions` providers."""

    def __init__(self, config: LLMConfig) -> None:
        self.config = config

    def chat_json(
        self,
        messages: list[ChatMessage],
        *,
        output_model: type[BaseModel] | None = None,
        tool_name: str = "structured_output",
        model: str | None = None,
    ) -> dict:
        """Return a JSON object generated by the model."""

        if not self.config.api_key:
            raise RuntimeError("OPENAI_COMPATIBLE_API_KEY is not configured")

        if (
            self.config.structured_output_mode == "strict_tool"
            and output_model is not None
        ):
            return self._chat_strict_tool(messages, output_model, tool_name, model=model)

        payload = {
            "model": model or self.config.model,
            "messages": [message.__dict__ for message in messages],
            "temperature": 0,
            "response_format": {"type": "json_object"},
        }
        if self.config.reasoning_effort != "none":
            payload["thinking"] = {"type": "enabled"}
            payload["reasoning_effort"] = self.config.reasoning_effort
        else:
            payload["thinking"] = {"type": "disabled"}
        data = self._post_chat(payload, self.config.base_url)

        content = data["choices"][0]["message"]["content"]
        return json.loads(content)

    def _chat_strict_tool(
        self,
        messages: list[ChatMessage],
        output_model: type[BaseModel],
        tool_name: str,
        *,
        model: str | None = None,
    ) -> dict:
        schema = _schema_for_strict_tool(output_model)
        payload: dict[str, Any] = {
            "model": model or self.config.model,
            "messages": [message.__dict__ for message in messages],
            "temperature": 0,
            "tools": [
                {
                    "type": "function",
                    "function": {
                        "name": tool_name,
                        "description": f"Return a validated {output_model.__name__} JSON object.",
                        "parameters": schema,
                        "strict": True,
                    },
                }
            ],
            "tool_choice": {
                "type": "function",
                "function": {"name": tool_name},
            },
        }
        if self.config.reasoning_effort != "none":
            raise RuntimeError(
                "DeepSeek strict tool calling does not support thinking mode; "
                "set OPENAI_COMPATIBLE_REASONING_EFFORT=none"
            )
        payload["thinking"] = {"type": "disabled"}
        data = self._post_chat(payload, self.config.beta_base_url)

        message = data["choices"][0]["message"]
        tool_calls = message.get("tool_calls") or []
        if not tool_calls:
            raise RuntimeError("LLM strict tool response did not include tool_calls")
        arguments = tool_calls[0].get("function", {}).get("arguments")
        if not isinstance(arguments, str):
            raise RuntimeError("LLM strict tool response did not include JSON arguments")
        try:
            return _loads_tool_arguments(arguments)
        except json.JSONDecodeError as exc:
            snippet = arguments[:500]
            raise RuntimeError(
                f"LLM strict tool arguments were not valid JSON: {exc}; "
                f"arguments_prefix={snippet!r}"
            ) from exc

    def _post_chat(self, payload: dict[str, Any], base_url: str) -> dict:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        request = urllib.request.Request(
            f"{base_url}/chat/completions",
            data=body,
            headers={
                "Authorization": f"Bearer {self.config.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.config.timeout_seconds) as response:
                data = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"LLM request failed with HTTP {exc.code}: {detail}") from exc

        return data


def _schema_for_strict_tool(model: type[BaseModel]) -> dict[str, Any]:
    schema = model.model_json_schema()
    definitions = schema.pop("$defs", {})
    schema = _inline_local_refs(schema, definitions)
    return _strip_unsupported_schema_keys(schema)


def _loads_tool_arguments(arguments: str) -> dict:
    try:
        parsed = json.loads(arguments)
    except json.JSONDecodeError:
        parsed = json_repair.loads(arguments)
    if not isinstance(parsed, dict):
        raise json.JSONDecodeError(
            "tool arguments must decode to a JSON object",
            arguments,
            0,
        )
    return parsed


def _inline_local_refs(value: Any, definitions: dict[str, Any]) -> Any:
    if isinstance(value, dict):
        ref = value.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/$defs/"):
            name = ref.rsplit("/", 1)[-1]
            target = definitions.get(name)
            if target is None:
                raise RuntimeError(f"unsupported local schema reference: {ref}")
            merged = {
                **_inline_local_refs(target, definitions),
                **{k: v for k, v in value.items() if k != "$ref"},
            }
            return merged
        return {k: _inline_local_refs(v, definitions) for k, v in value.items()}
    if isinstance(value, list):
        return [_inline_local_refs(item, definitions) for item in value]
    return value


def _strip_unsupported_schema_keys(value: Any) -> Any:
    unsupported = {"title", "default", "examples"}
    if isinstance(value, dict):
        return {
            key: _strip_unsupported_schema_keys(item)
            for key, item in value.items()
            if key not in unsupported
        }
    if isinstance(value, list):
        return [_strip_unsupported_schema_keys(item) for item in value]
    return value
