"""Minimal OpenAI-compatible chat completion client.

The project intentionally avoids depending on the OpenAI SDK in phase 1 so the
file pipeline can run with only the standard library plus pydantic.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from dataclasses import dataclass

from law_agent.config import LLMConfig


@dataclass(frozen=True)
class ChatMessage:
    role: str
    content: str


class OpenAICompatibleClient:
    """Small client for `/chat/completions` providers."""

    def __init__(self, config: LLMConfig) -> None:
        self.config = config

    def chat_json(self, messages: list[ChatMessage]) -> dict:
        """Return a JSON object generated by the model."""

        if not self.config.api_key:
            raise RuntimeError("OPENAI_COMPATIBLE_API_KEY is not configured")

        payload = {
            "model": self.config.model,
            "messages": [message.__dict__ for message in messages],
            "temperature": 0,
            "response_format": {"type": "json_object"},
        }
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        request = urllib.request.Request(
            f"{self.config.base_url}/chat/completions",
            data=body,
            headers={
                "Authorization": f"Bearer {self.config.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.config.timeout_seconds) as response:
                data = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"LLM request failed with HTTP {exc.code}: {detail}") from exc

        content = data["choices"][0]["message"]["content"]
        return json.loads(content)
