/**
 * TypeScript type definitions for the LawAgent review API.
 *
 * These interfaces mirror the Pydantic response models exposed by the
 * FastAPI backend in `law_agent/review/api.py` and its dependencies
 * (`law_agent/review/schemas.py`, `law_agent/review/evalset/schemas.py`,
 * `law_agent/data/schemas.py`).
 *
 * Field names and JSON shapes are kept in sync with the backend so that
 * responses can be consumed directly without any client-side mapping.
 */

// ---------------------------------------------------------------------------
// Shared literal union types
// ---------------------------------------------------------------------------

/** Risk level reported by a review result. */
export type RiskLevel =
  | 'high'
  | 'medium'
  | 'low'
  | 'insufficient_evidence';

/** Usage category for a group of citations. */
export type CitationUsage =
  | 'legal_basis'
  | 'conditional_basis'
  | 'implementation_reference'
  | 'policy_explanation';

/** Role a clause citation plays in the legal argument. */
export type ClauseCitationRole =
  | 'primary_legal_basis'
  | 'conditional_local_basis'
  | 'conditional_industry_basis'
  | 'implementation_reference'
  | 'interpretation_auxiliary';

/** Status of the evidence sufficiency self-check. */
export type EvidenceStatus =
  | 'not_checked'
  | 'sufficient'
  | 'needs_second_retrieval'
  | 'insufficient';

/** Concrete issue types detected during the evidence self-check. */
export type EvidenceIssueType =
  | 'no_primary_legal_basis'
  | 'region_mismatch'
  | 'industry_mismatch'
  | 'only_auxiliary_evidence'
  | 'cross_border_mismatch'
  | 'critical_facts_missing';

/** Retrieval query type generated by the planner. */
export type RetrievalQueryType =
  | 'legal_issue'
  | 'material_fact'
  | 'region_condition'
  | 'industry_condition'
  | 'missing_information';

/** Retriever name used to produce a hit. */
export type RetrieverName =
  | 'keyword'
  | 'vector_mock'
  | 'hybrid'
  | 'elasticsearch'
  | 'pgvector';

/** Evaluation retrieval backend under test. */
export type EvalRetrievalMode = 'service' | 'local';

/** Evaluation review owner under test. */
export type EvalReviewMode = 'llm' | 'local';

/** Optional post-fusion reranker arm for A/B evaluation. */
export type EvalRerankMode = 'off' | 'embedding';

/** Evaluation scenario subset. */
export type EvalSuite = 'quick' | 'base' | 'full';

// ---------------------------------------------------------------------------
// Review domain models
// ---------------------------------------------------------------------------

/**
 * Structured facts extracted from the user-supplied material.
 *
 * Matches `ReviewFacts` in `law_agent/review/schemas.py`. All optional
 * fields are `null` when the fact could not be inferred from the material.
 */
export interface ReviewFacts {
  /** High-level description of the business activity, if detected. */
  business_activity: string | null;
  /** Data categories referenced by the material (e.g. "personal_info"). */
  data_types: string[];
  /** Whether sensitive personal information is involved. */
  sensitive_personal_info: boolean | null;
  /** Whether cross-border data transfer is involved. */
  cross_border_transfer: boolean | null;
  /** The overseas recipient, if any. */
  overseas_recipient: string | null;
  /** Stated processing purpose. */
  processing_purpose: string | null;
  /** Legal basis or consent description claimed by the material. */
  legal_basis_or_consent: string | null;
  /** Industry context (e.g. "finance", "healthcare"). */
  industry: string | null;
  /** Geographic region context (e.g. "CN", "EU"). */
  region: string | null;
  /** Facts that could not be determined and should be requested from the user. */
  missing_information: string[];
}

/**
 * A governed citation selected for a review result.
 *
 * Matches `Citation` in `law_agent/review/schemas.py`.
 */
export interface Citation {
  source_id: string;
  chunk_id: string;
  title: string;
  source_url: string;
  citation_role: ClauseCitationRole;
  /** Whether this citation may be quoted as a formal clause. */
  can_cite_clause: boolean;
  usage: CitationUsage;
  /** Human-readable label for the citation (e.g. "《个人信息保护法》第38条"). */
  citation_label: string | null;
}

/**
 * A group of citations sharing the same usage category.
 *
 * Matches `CitationGroup` in `law_agent/review/schemas.py`.
 */
export interface CitationGroup {
  usage: CitationUsage;
  citations: Citation[];
  /** Optional note describing the scope of this group. */
  scope_note: string | null;
}

/**
 * A specific evidence sufficiency issue detected during self-check.
 *
 * Matches `EvidenceIssue` in `law_agent/review/schemas.py`.
 */
export interface EvidenceIssue {
  issue_type: EvidenceIssueType;
  description: string;
}

/**
 * A typed query generated for retrieval.
 *
 * Matches `RetrievalQuery` in `law_agent/review/schemas.py`. Referenced by
 * `SecondRetrievalPlan.expanded_queries`.
 */
export interface RetrievalQuery {
  query_id: string;
  query_type: RetrievalQueryType;
  text: string;
}

/**
 * A scored evidence hit returned by a retriever.
 *
 * Matches `RetrievalHit` in `law_agent/review/schemas.py`. Surfaced in the
 * review response as `evidence_chunks` so the frontend can expand a citation
 * to show the underlying clause text, source URL, and retrieval metadata.
 */
export interface RetrievalHit {
  chunk_id: string;
  doc_id: string;
  source_id: string;
  title: string;
  text: string;
  score: number;
  rank: number;
  retriever: RetrieverName;
  citation_role: ClauseCitationRole;
  can_cite_clause: boolean;
  source_url: string;
  matched_query_type: RetrievalQueryType | null;
}

/**
 * Chunk-level evidence retained for one selected source.
 *
 * The backend uses source-aware fusion to pick diverse sources, then attaches
 * same-source supporting chunks and neighbor chunks so the report and UI keep
 * the precise passages behind each source.
 */
export interface SourceEvidencePacket {
  source_id: string;
  title: string;
  representative_chunk: RetrievalHit;
  supporting_chunks: RetrievalHit[];
  neighbor_chunks: RetrievalHit[];
}

/**
 * Plan for one controlled second retrieval when evidence is weak.
 *
 * Matches `SecondRetrievalPlan` in `law_agent/review/schemas.py`.
 */
export interface SecondRetrievalPlan {
  expanded_queries: RetrievalQuery[];
  increased_top_k: number;
  stronger_boost: boolean;
  reason: string;
}

/**
 * Evidence sufficiency state for a review trace.
 *
 * Matches `EvidenceSelfCheck` in `law_agent/review/schemas.py`.
 */
export interface EvidenceSelfCheck {
  status: EvidenceStatus;
  issues: EvidenceIssue[];
  triggered_reasons: string[];
  second_retrieval_triggered: boolean;
  /** Present only when a second retrieval is planned. */
  second_retrieval_plan: SecondRetrievalPlan | null;
}

/**
 * Structured review result produced from facts and evidence.
 *
 * Matches `ReviewResult` in `law_agent/review/schemas.py`.
 */
export interface ReviewResult {
  review_result_id: string;
  review_case_id: string;
  trace_id: string;
  risk_level: RiskLevel;
  conclusion: string;
  review_facts: ReviewFacts;
  trigger_reasons: string[];
  missing_information: string[];
  recommended_actions: string[];
  risk_boundaries: string[];
  citations: Citation[];
  /** Evidence grouped by usage category. */
  applicable_evidence: CitationGroup[];
}

/**
 * Response body for `POST /api/review`.
 *
 * Matches `ReviewResponse` in `law_agent/review/api.py`.
 */
export interface ReviewResponse {
  review_case_id: string;
  trace_id: string;
  review_facts: ReviewFacts;
  review_result: ReviewResult;
  evidence_self_check: EvidenceSelfCheck;
  /** Same value as `review_result.applicable_evidence`, surfaced for convenience. */
  citation_groups: CitationGroup[];
  second_retrieval_triggered: boolean;
  /** Typed retrieval queries planned from the question + facts (query plan). */
  retrieval_queries?: RetrievalQuery[];
  /** Final evidence hits with chunk text, used to expand citations inline. */
  evidence_chunks: RetrievalHit[];
  /** Source-level evidence packets with representative/supporting/neighbor chunks. */
  source_evidence_packets: SourceEvidencePacket[];
}

/**
 * Structured failure response for LLM-owned workflow nodes.
 *
 * The backend intentionally returns this as HTTP 200 so the UI can display
 * which node failed after retries instead of treating it as transport failure.
 */
export interface ReviewFailedResponse {
  status: 'review_failed';
  failed_node: string;
  reason: string;
  message: string;
  attempts: number;
  trace_id: string | null;
}

/** Response body for `POST /api/review`. */
export type ReviewApiResponse = ReviewResponse | ReviewFailedResponse;

export function isReviewFailedResponse(
  response: ReviewApiResponse | null,
): response is ReviewFailedResponse {
  return Boolean(response && 'status' in response && response.status === 'review_failed');
}

/**
 * Response body for `GET /api/health`.
 *
 * Matches `HealthResponse` in `law_agent/review/api.py`.
 */
export interface HealthResponse {
  status: string;
}

// ---------------------------------------------------------------------------
// Evaluation suite models
// ---------------------------------------------------------------------------

/**
 * Metrics for a single evaluation scenario case.
 *
 * Matches `CaseMetricResult` in `law_agent/review/evalset/schemas.py`.
 */
export interface CaseMetricResult {
  case_id: string;
  recall_at_3: number;
  recall_at_5: number;
  mrr_at_10: number;
  candidate_recall_at_50: number;
  distinct_source_recall_at_5: number;
  duplicate_source_count_at_10: number;
  citation_violation_count: number;
  abstention_correct: boolean;
  /** 是否触发了二次检索。 */
  second_retrieval_triggered: boolean;
  /** Source IDs actually retrieved by the system. */
  actual_sources: string[];
  /** Expected source IDs that were missing from the results. */
  missing_sources: string[];
  is_bad_case: boolean;
  bad_reasons: string[];
  risk_level: string;
}

/**
 * Aggregated metrics for one retrieval mode.
 *
 * Matches `ModeMetrics` in `law_agent/review/evalset/schemas.py`.
 */
export interface ModeMetrics {
  mode: string;
  mean_recall_at_3: number;
  mean_recall_at_5: number;
  mean_mrr_at_10: number;
  mean_candidate_recall_at_50: number;
  mean_distinct_source_recall_at_5: number;
  mean_duplicate_source_count_at_10: number;
  abstention_accuracy: number;
  /** 诊断指标：二次检索触发率（不计坏例）。 */
  second_retrieval_trigger_rate: number;
  total_citation_violations: number;
  bad_case_count: number;
  total_cases: number;
}

/**
 * Full evaluation summary output.
 *
 * Matches `EvalSummary` in `law_agent/review/evalset/schemas.py`. Returned
 * by both `POST /api/eval/run` and `GET /api/eval/latest`.
 */
export interface EvalSummary {
  generated_at: string;
  chunks_path: string;
  cases_path: string;
  /** Aggregated metrics keyed by explicit eval axes. */
  mode_metrics: Record<string, ModeMetrics>;
  bad_cases: CaseMetricResult[];
  /** Per-case results keyed by mode name. */
  all_case_results: Record<string, CaseMetricResult[]>;
}

/** Request body for `POST /api/eval/run`. */
export interface EvalRunOptions {
  chunks_path?: string;
  retrieval_mode?: EvalRetrievalMode;
  review_mode?: EvalReviewMode;
  top_k?: number;
  max_workers?: number;
  rerank_mode?: EvalRerankMode;
  suite?: EvalSuite;
}

export type EvalJobStatus = 'idle' | 'running' | 'succeeded' | 'failed';

export interface EvalJobResponse {
  job_id: string | null;
  status: EvalJobStatus;
  message: string | null;
  started_at: string | null;
  finished_at: string | null;
}
